"""empty message

Revision ID: 3f41dd35499c
Revises: 
Create Date: 2023-05-29 19:44:52.504165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f41dd35499c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('ip_port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.Enum('UNKNOWN', 'SOCKS4', 'SOCKS5', 'HTTP', 'HTTPS', name='proxyprotocol'), nullable=True),
    sa.Column('login', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('anonymity_level', sa.Integer(), nullable=True),
    sa.Column('latency', sa.Integer(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('proxy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connections', sa.Integer(), nullable=True),
    sa.Column('failed_connections', sa.Integer(), nullable=True),
    sa.Column('last_tested', sa.DateTime(), nullable=True),
    sa.Column('proxy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health')
    op.drop_table('address')
    op.drop_table('proxy')
    # ### end Alembic commands ###
