"""empty message

Revision ID: ff1e967acb17
Revises: 3f41dd35499c
Create Date: 2023-05-31 14:43:15.723902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1e967acb17'
down_revision = '3f41dd35499c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint('address_proxy_id_fkey', type_='foreignkey')
        batch_op.drop_column('proxy_id')

    with op.batch_alter_table('health', schema=None) as batch_op:
        batch_op.drop_constraint('health_proxy_id_fkey', type_='foreignkey')
        batch_op.drop_column('proxy_id')

    with op.batch_alter_table('proxy', schema=None) as batch_op:
        batch_op.execute("ALTER TYPE proxyprotocol RENAME TO sqlproxyprotocol")

        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('health_id', sa.Integer(), nullable=True))
        batch_op.alter_column('protocol', nullable=False)
        # batch_op.alter_column('protocol',
        #        existing_type=sa.Enum('UNKNOWN', 'SOCKS4', 'SOCKS5', 'HTTP', 'HTTPS', name="proxyprotocol", create_type=False),
        #        type_=sa.Enum('UNKNOWN', 'SOCKS4', 'SOCKS5', 'HTTP', 'HTTPS', name="sqlproxyprotocol", create_type=False),
        #        nullable=False)
        batch_op.create_unique_constraint("proxy_ip_address_ip_port_protocol_key", ['ip_address', 'ip_port', 'protocol'])
        batch_op.create_foreign_key("proxy_address_id_fkey", 'address', ['address_id'], ['id'])
        batch_op.create_foreign_key("proxy_health_id_fkey", 'health', ['health_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proxy', schema=None) as batch_op:
        batch_op.drop_constraint("proxy_health_id_fkey", type_='foreignkey')
        batch_op.drop_constraint("proxy_address_id_fkey", type_='foreignkey')
        batch_op.drop_constraint("proxy_ip_address_ip_port_protocol_key", type_='unique')

        batch_op.execute("ALTER TYPE sqlproxyprotocol RENAME TO proxyprotocol")

        # batch_op.alter_column('protocol',
        #        existing_type=sa.Enum('UNKNOWN', 'SOCKS4', 'SOCKS5', 'HTTP', 'HTTPS', name="sqlproxyprotocol", create_type=False),
        #        type_=sa.Enum('UNKNOWN', 'SOCKS4', 'SOCKS5', 'HTTP', 'HTTPS', name="proxyprotocol", create_type=False),
        #        nullable=True)
        batch_op.alter_column('protocol', nullable=True)
        batch_op.drop_column('health_id')
        batch_op.drop_column('address_id')

    with op.batch_alter_table('health', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proxy_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('health_proxy_id_fkey', 'proxy', ['proxy_id'], ['id'])

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proxy_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('address_proxy_id_fkey', 'proxy', ['proxy_id'], ['id'])

    # ### end Alembic commands ###
